[tool.bumpversion]
current_version = "1.0.0"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "Cargo.toml"

[[tool.bumpversion.files]]
filename = "Cargo.lock"
search = '''name = "neowright"
version = "{current_version}"'''
replace = '''name = "neowright"
version = "{new_version}"'''

[[tool.bumpversion.files]]
filename = "README.md"
search = "--tag v{current_version}"
replace = "--tag v{new_version}"
